-- ════════════════════════════════════════════════════════════════════════
--  007_seed_distribution_list.sql
--  Seed the publish distribution list from the RAID recipient list
--  (Outlook recipient export, September 2026). 187 unique addresses;
--  emails lower-cased to match the API's normalisation. Idempotent:
--  re-running skips addresses already present.
-- ════════════════════════════════════════════════════════════════════════

insert into distribution_list (name, email) values
  ('Aimi Morris', 'aimi.morris@networkrail.co.uk'),
  ('Alexandra Greig-Cooper', 'alexandra.greig-cooper@eastmidlandsrailway.co.uk'),
  ('Amy Turnbull', 'amy.turnbull@networkrail.co.uk'),
  ('Andrew Briddon', 'andrew.briddon@eastmidlandsrailway.co.uk'),
  ('Andrew LeBaigue', 'andrew.lebaigue@gtrailway.com'),
  ('Andrew Smith', 'andrew.smith4@networkrail.co.uk'),
  ('Andrew Sneesby', 'andrew.sneesby@networkrail.co.uk'),
  ('Andy Bell', 'andy.bell@eastmidlandsrailway.co.uk'),
  ('Andy Howard', 'andy.howard@eastmidlandsrailway.co.uk'),
  ('Andy Taylor', 'andy.taylor@networkrail.co.uk'),
  ('Angie Reed', 'angie.reed@eastmidlandsrailway.co.uk'),
  ('Barclay O''Malley', 'barclay.o''malley@networkrail.co.uk'),
  ('Barry Carney', 'barry.carney@hitachirail.com'),
  ('Ben Eddy', 'ben.eddy@eastmidlandsrailway.co.uk'),
  ('Ben Kinnear', 'ben.kinnear@networkrail.co.uk'),
  ('Ben Slade', 'ben.slade@eastmidlandsrailway.co.uk'),
  ('Bronwyn Clarke', 'bronwyn.clarke@networkrail.co.uk'),
  ('Charlotte Rose', 'charlotte.rose1@networkrail.co.uk'),
  ('Charlotte White', 'charlotte.white@eastmidlandsrailway.co.uk'),
  ('Cheryl Goddard', 'cheryl.goddard@eastmidlandsrailway.co.uk'),
  ('Chevaughn Weston', 'chevaughn.weston@eastmidlandsrailway.co.uk'),
  ('Chloe Tryka', 'chloe.tryka@networkrail.co.uk'),
  ('Chris Gee', 'chris.gee3@networkrail.co.uk'),
  ('Chris Levett', 'chris.levett2@networkrail.co.uk'),
  ('Chris Sharp', 'chris.sharp@networkrail.co.uk'),
  ('Christopher Smith', 'christopher.smith3@networkrail.co.uk'),
  ('Clemente Vacchio', 'clemente.vacchio@networkrail.co.uk'),
  ('Colin Ord', 'colin.ord@gtrailway.com'),
  ('Colin Parsons', 'colin.parsons@gtrailway.com'),
  ('Craig Gascoyne', 'craig.gascoyne@eastmidlandsrailway.co.uk'),
  ('Craig Leaper', 'craig.leaper@eastmidlandsrailway.co.uk'),
  ('Grant Hobbs', 'grant.hobbs@networkrail.co.uk'),
  ('Craig Merry', 'craig.merry@networkrail.co.uk'),
  ('Cristiana Radu', 'cristiana.radu@networkrail.co.uk'),
  ('Daniel Evans', 'daniel.evans@networkrail.co.uk'),
  ('Daniel Hughes', 'daniel.hughes@eastmidlandsrailway.co.uk'),
  ('Daniel Matthews', 'daniel.matthews@networkrail.co.uk'),
  ('Daniel Schofield', 'daniel.schofield@networkrail.co.uk'),
  ('Danielle Clarke', 'danielle.clarke@eastmidlandsrailway.co.uk'),
  ('Danielle Healy', 'danielle.healy@networkrail.co.uk'),
  ('Danni Blavins', 'danni.blavins@eastmidlandsrailway.co.uk'),
  ('Darren Edmonds', 'darren.edmonds@networkrail.co.uk'),
  ('Darren Field-Thomas', 'darren.field-thomas@eastmidlandsrailway.co.uk'),
  ('Dave Meredith', 'dave.meredith@eastmidlandsrailway.co.uk'),
  ('David Bowden', 'david.bowden2@networkrail.co.uk'),
  ('David Burgess', 'david.burgess@eastmidlandsrailway.co.uk'),
  ('Derby Control', 'control.derby@networkrail.co.uk'),
  ('Dominic Jofirisi', 'dominic.jofirisi@networkrail.co.uk'),
  ('DSDM', 'dutyservicedeliverymanager@eastmidlandsrailway.co.uk'),
  ('Ellis Savage', 'ellis.savage@networkrail.co.uk'),
  ('Emma Winson-Yates', 'emma.winsonyates@hitachirail.com'),
  ('DNOM GTR', 'roc-dnom@gtrailway.com'),
  ('Kim Griffin', 'kim.griffin@gtrailway.com'),
  ('Nadia Paul', 'nadia.paul@gtrailway.com'),
  ('Network Operations Head of', 'roc-hono@gtrailway.com'),
  ('Owen Nathaniel', 'nathaniel.owen@gtrailway.com'),
  ('Paul Codd', 'paul.codd@gtrailway.com'),
  ('ROC CSC (GTR Railway)', 'roc-cscm@gtrailway.com'),
  ('Sara Turner', 'sara.turner@gtrailway.com'),
  ('Sarah Jones', 'sarah.jones@gtrailway.com'),
  ('Yandell Antony', 'antony.yandell@gtrailway.com'),
  ('Gareth Pearson', 'gareth.pearson@networkrail.co.uk'),
  ('Gareth Race', 'gareth.race@hitachirail.com'),
  ('Garry Straw', 'garry.straw@networkrail.co.uk'),
  ('Gary Allison', 'gary.allison@networkrail.co.uk'),
  ('Gary Lilliman', 'gary.lilliman@networkrail.co.uk'),
  ('Gary Roberts', 'gary.roberts@networkrail.co.uk'),
  ('Gary Vickers', 'gary.vickers@networkrail.co.uk'),
  ('Gavin Green', 'gavin.green@networkrail.co.uk'),
  ('Gavin Thomas', 'gavin.thomas@eastmidlandsrailway.co.uk'),
  ('Glyn Williams', 'glyn.williams@networkrail.co.uk'),
  ('Greg Woodbridge', 'greg.woodbridge@networkrail.co.uk'),
  ('Hadyn Deardon', 'hadyn.deardon@networkrail.co.uk'),
  ('Ian Coleman', 'ian.coleman2@networkrail.co.uk'),
  ('Ieuan Halliday', 'ieuan.halliday@networkrail.co.uk'),
  ('Jack Bloomfield', 'jack.bloomfield@networkrail.co.uk'),
  ('Jacky Stevens', 'jacky.stevens@networkrail.co.uk'),
  ('James Weston', 'james.weston@eastmidlandsrailway.co.uk'),
  ('Jamie Yates', 'jamie.yates@eastmidlandsrailway.co.uk'),
  ('Jason Cocker', 'jason.cocker@eastmidlandsrailway.co.uk'),
  ('Jason Wardell', 'jason.wardell@networkrail.co.uk'),
  ('Jemmabeth', 'jemmabeth.southerton@eastmidlandsrailway.co.uk'),
  ('', 'jenna.galiszewski@eastmidlandsrailway.co.uk'),
  ('Jim Mansfield', 'jim.mansfield2@networkrail.co.uk'),
  ('Jon Rolling', 'jonathan.rolling@eastmidlandsrailway.co.uk'),
  ('Joseph Carter', 'joseph.carter@networkrail.co.uk'),
  ('Kinga Kolasinska', 'kinga.kolasinska@gtrailway.com'),
  ('Klay Wellington Knight', 'klay.wellington-knight@gtrailway.com'),
  ('Krishna Krishna Nivas Raj', 'krishna.krishnanivasraj@networkrail.co.uk'),
  ('Kyle Pratt', 'kyle.pratt@eastmidlandsrailway.co.uk'),
  ('Lee Hannibal', 'lee.hannibal@networkrail.co.uk'),
  ('Leigh Owen-Vaz', 'leigh.owen-vaz@networkrail.co.uk'),
  ('Liam Powell-Jones', 'liam.powell-jones@eastmidlandsrailway.co.uk'),
  ('Lucan Hawes', 'lucan.hawes@networkrail.co.uk'),
  ('Lucy Gallacher', 'lucy.gallacher@eastmidlandsrailway.co.uk'),
  ('Malcolm Arnold', 'malcolm.arnold@networkrail.co.uk'),
  ('Marc Cooper', 'marc.cooper@networkrail.co.uk'),
  ('Mark Bridel', 'mark.bridel@networkrail.co.uk'),
  ('Mark Budden', 'mark.budden@networkrail.co.uk'),
  ('Mark Burton', 'mark.burton1@gtrailway.com'),
  ('Mark Coney', 'mark.coney@eastmidlandsrailway.co.uk'),
  ('Mark Donkin', 'mark.donkin@eastmidlandsrailway.co.uk'),
  ('Mark Elliott', 'mark.elliott@eastmidlandsrailway.co.uk'),
  ('Mark Evans', 'mark.evans@eastmidlandsrailway.co.uk'),
  ('Mat Healey', 'mat.healey@eastmidlandsrailway.co.uk'),
  ('Matthew Stacey', 'matthew.stacey@eastmidlandsrailway.co.uk'),
  ('', 'michael.webb@eastmidlandsrailway.co.uk'),
  ('Michelle Gull', 'michelle.gull@networkrail.co.uk'),
  ('Michelle Portas', 'michelle.portas@eastmidlandsrailway.co.uk'),
  ('Mike O''Callaghan', 'mike.ocallaghan@eastmidlandsrailway.co.uk'),
  ('Mike Pybus', 'mike.pybus@networkrail.co.uk'),
  ('Morinoye Folorunso', 'morinoye.folorunso@networkrail.co.uk'),
  ('Natasha Carter', 'natasha.carter@networkrail.co.uk'),
  ('Natasha Wilkinson', 'natasha.wilkinson@networkrail.co.uk'),
  ('Nathan ONeill', 'nathan.oneill@networkrail.co.uk'),
  ('Neil Teather', 'neil.teather@networkrail.co.uk'),
  ('Nicholas Fordham', 'nicholas.fordham@networkrail.co.uk'),
  ('Nicholas Rodrigues', 'nicholas.rodrigues@networkrail.co.uk'),
  ('Nick Allen', 'nick.allen@crosscountrytrains.co.uk'),
  ('Nick Allsop', 'nick.allsop@networkrail.co.uk'),
  ('Nick Arter', 'nick.arter@networkrail.co.uk'),
  ('Nick Shaw', 'nick.shaw@gtrailway.co.uk'),
  ('Nick Taylor', 'nick.taylor@networkrail.co.uk'),
  ('Nigel Pearson', 'nigel.pearson@networkrail.co.uk'),
  ('Nigel Symms', 'nigel.symms@networkrail.co.uk'),
  ('Nina McGovern', 'nina.mcgovern@gtrailway.com'),
  ('Oliver Starbuck', 'oliver.starbuck@eastmidlandsrailway.co.uk'),
  ('Paul Heron', 'paul.heron@networkrail.co.uk'),
  ('Paul Jones', 'paul.jones@eastmidlandsrailway.co.uk'),
  ('Paula Cunningham', 'paula.cunningham@networkrail.co.uk'),
  ('Peter Belton', 'peter.belton@networkrail.co.uk'),
  ('Peter Green', 'peter.green3@networkrail.co.uk'),
  ('Peter Robinson', 'peter.robinson4@networkrail.co.uk'),
  ('Qianqian Li', 'qianqian.li@networkrail.co.uk'),
  ('Rachel Biggs', 'rachel.biggs@eastmidlandsrailway.co.uk'),
  ('Rachel McGinley', 'rachel.mcginley@eastmidlandsrailway.co.uk'),
  ('Rachel McGough', 'rachel.mcgough@eastmidlandsrailway.co.uk'),
  ('Rachel Rundell', 'rachel.rundell@eastmidlandsrailway.co.uk'),
  ('Rebbecca Brown', 'rebbecca.brown@eastmidlandsrailway.co.uk'),
  ('Rhea Nakkidepu', 'rhea.nakkidepu@networkrail.co.uk'),
  ('', 'richard.surgey@eastmidlandsrailway.co.uk'),
  ('Rob Drysdale', 'robert.drysdale@btp.police.uk'),
  ('Rob Mason', 'rob.mason@eastmidlandsrailway.co.uk'),
  ('Rob Mercer', 'rob.mercer@eastmidlandsrailway.co.uk'),
  ('Robertson Paul', 'paul.robertson@networkrail.co.uk'),
  ('Rod Fawcett', 'rod.fawcett@eastmidlandsrailway.co.uk'),
  ('Roshan Patel', 'roshan.patel@eastmidlandsrailway.co.uk'),
  ('Russell Totten', 'russell.totten@networkrail.co.uk'),
  ('Ryan Morris', 'ryan.morris@btp.police.uk'),
  ('Sam Clements', 'sam.clements@eastmidlandsrailway.co.uk'),
  ('Sam Jones', 'sam.jones@eastmidlandsrailway.co.uk'),
  ('Sam Minion', 'sam.minion@networkrail.co.uk'),
  ('Samantha Clews', 'samantha.clews@networkrail.co.uk'),
  ('Sarah Turner', 'sarah.turner@eastmidlandsrailway.co.uk'),
  ('Simon Payne', 'simon.payne@networkrail.co.uk'),
  ('SNDM_Derby', 'sndm_derby@networkrail.co.uk'),
  ('Sophie Hammond', 'sophie.hammond@eastmidlandsrailway.co.uk'),
  ('Sophie Jackson', 'sophie.jackson@networkrail.co.uk'),
  ('Stephen O''Connell', 'stephen.o''connell@networkrail.co.uk'),
  ('Steve Hannibal', 'steve.hannibal@networkrail.co.uk'),
  ('Steven Dolby', 'steven.dolby@networkrail.co.uk'),
  ('Stuart Teebay', 'stuart.tebay@eastmidlandsrailway.co.uk'),
  ('Sufyaan Mullaji', 'sufyaan.mullaji@eastmidlandsrailway.co.uk'),
  ('Tara Scott', 'tara.scott@networkrail.co.uk'),
  ('Thomas Flaherty', 'thomas.flaherty@eastmidlandsrailway.co.uk'),
  ('Thomas Kemp', 'thomas.kemp@networkrail.co.uk'),
  ('Tim Garbutt', 'tim.garbutt@eastmidlandsrailway.co.uk'),
  ('Tim Turner', 'tim.turner@networkrail.co.uk'),
  ('Timothy Denton', 'timothy.denton@eastmidlandsrailway.co.uk'),
  ('Tina Owusu', 'tina.owusu@gtrailway.com'),
  ('Tom Aubertin', 'tom.aubertin@eastmidlandsrailway.co.uk'),
  ('Tom Jones', 'tom.jones@eastmidlandsrailway.co.uk'),
  ('Tommy Puncheon', 'tommy.puncheon3@networkrail.co.uk'),
  ('Tony Oliver', 'tony.oliver@gtrailway.com'),
  ('Wendy Cunningham', 'wendy.cunningham@eastmidlandsrailway.co.uk'),
  ('West Hampstead Performance', 'whperf@networkrail.co.uk'),
  ('West Hampstead PSB', 'westhamp.control@networkrail.co.uk'),
  ('Yaw Akuamoa', 'yaw.akuamoa@networkrail.co.uk'),
  ('Yvonne Clay', 'yvonne.clay@eastmidlandsrailway.co.uk'),
  ('Graeme Campbell', 'graeme.campbell@eastmidlandsrailway.co.uk'),
  ('EM ILR inbox', 'emilrinbox@networkrail.co.uk'),
  ('Mark Boon', 'mark.boon@gtrailway.com'),
  ('Operations Delivery Manager', 'operationsdeliverymanager@eastmidlandsrailway.co.uk'),
  ('Andrew Monk', 'andrew.monk@gtrailway.com'),
  ('Danielle Blavins', 'danielle.blavins@eastmidlandsrailway.co.uk'),
  ('Matthew Gee', 'matthew.gee@gtrailway.com'),
  ('Dan Guild', 'dan.guild@networkrail.co.uk')
on conflict (email) do nothing;
